jaredpar/complog

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, src/Basic.CompilerLog.Util/SolutionReader.cs, src/Scratch/Program.cs
There are two main issues fixed here:
1. Handling all the content kind
2. De-duping references when building `ProjectInfo` entries
=> Fix issues loading roslyn compiler log

.vscode/settings.json, Directory.Build.props, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.Util/BasicAnalyzers.cs, src/Basic.CompilerLog.Util/BinaryLogUtil.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/CompilerLogUtil.cs, src/Basic.CompilerLog/Program.cs, src/Scratch/Program.cs
Changes:
- Move to reading raw records to speed up performance on large binlog files
- Fixed a number of typos
- Cleaned up API names to be more consistent with .NET designs
=> Couple of cleanups

src/Basic.CompilerLog.UnitTests/BasicAnalyzerHostTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.Util/BasicAnalyzerHost.cs, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/CompilerLogState.cs, src/Basic.CompilerLog.Util/CompilerLogUtil.cs, src/Basic.CompilerLog/Program.cs
Two fixes here:
1. Make strong name key storage just work when reading info. No need to explicitly pass around storage dirs
2. Clarifies the ownership model for analyzer hosts, disk artifacts, etc ... for CompilerLogReader instances
closes #31
=> Better strong name key storage

src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/EmitData.cs, src/Basic.CompilerLog.Util/Extensions.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostInMemory.cs, src/Basic.CompilerLog/Program.cs, src/Shared/DotnetUtil.cs
Couple changes:
- Adds simple helpers for emitting the compilation into memory or disk. 
- Adds an `emit` command that emits all binaries in the compiler log. This is helpful for testing the tool is working correctly.
closes #30
=> Emit helpers

src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.Util/BinaryLogUtil.cs, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog.Util/CompilerCall.cs, src/Basic.CompilerLog.Util/SolutionReader.cs, src/Basic.CompilerLog/FilterOptionSet.cs, src/Basic.CompilerLog/Program.cs, src/Shared/DotnetUtil.cs
Pull request #41 revealed that the tool isn't handling all compilations in the binary log. It was only handling the subset that was pre-recognized by the tool heuristics. This PR changes the tool to instead handle all compilations and then categorize them by the same heuristic. There is a new `Unknown` bucket for the ones unrecognized by the tool that can be used.
=> Handle more compiler calls

src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/SolutionReaderTests.cs, src/Basic.CompilerLog.UnitTests/TempDir.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/RawCompilationData.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog.Util/SolutionReader.cs, src/Scratch/Program.cs, src/Shared/DotnetUtil.cs
This rounds out a few of the corner cases in `#line` directive support. 
The one issue that remains is when the user combines `/embed` and `#line` directives with full paths the resulting compilation is not 100% portable between machines. There is simply no way to redirect where the compiler attempts to read the target off of disk hence we're stuck with the original path. Filed [a bug](https://github.com/dotnet/roslyn/issues/69659) with roslyn to track fixing this.
=> Round out the line directive support

.vscode/launch.json, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog/FilterOptionSet.cs, src/Basic.CompilerLog/Program.cs
Build files can now be the targets of commands. So you can now say `complog create console.csproj`. Under the hood the tool will run `dotnet build`, grab the binary log and process that for the command. Should simplify a lot of scenarios.
=> Support project files for command targets

.github/workflows/dotnet.yml
Observed it's run unnecessarily in https://github.com/jaredpar/basic-compilerlog/pull/63
=> Avoid running CI for doc only changes

.vscode/launch.json, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Scratch/Scratch.cs
The .NET SDK produces a file name with = and , characters inside it on every build. Example:
> net472\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs
This file will be quoted when passed as an argument to say `/embed` and the existing logic was causing the entire option to be quoted.
=> Fixed embed bug

src/Shared/DotnetUtil.cs, src/Shared/ProcessUtil.cs
My home box has both the 7.0.400 and 8.0.100 RC2 .NET SDKs installed. This ended up revealing a subtle bug in the CLI when executing `dotnet test`.
The test content in this repo generates a global.json that pins the SDK to 7.0.400. That is done for consistency in testing across developer machines and CI. The repository itself has no global.json file so it floats to the _latest_ .NET SDK.
This combination revealed an odd bug in MSBuild. When executing `dotnet test` the CLI ended up spawning a `dotnet` that sets the `%MSBuildSDKsPath%` environment variable. Because `dotnet` spawned as an 8.0 process it set that path to the 8.0 SDK.
When executing the `dotnet new` actions inside the tests the global.json was read by the runtime host and ended up spawning a `dotnet` process from the 7.0 …
=> Fix bug mixing .NET SDKs

src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/CompilerCall.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/ExportUtil.cs
The options testing was using `CommandLineArguments.Parse` after content was deleted off of disk. That fails for certain operations like when a ruleset file is used. To fix this just moved the option round trip testing to the point of creation of the compiler log and that fixed the issue.
=> Fixed testing issue

src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/TempDir.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/RawCompilationData.cs, src/Basic.CompilerLog.Util/SolutionReader.cs
The `CompilationData` returned from a `CompilerLogReader` need to be tied to the state not the reader if the state isn't owned by the reader.
=> Fix bug with separate state

.gitignore, .vscode/launch.json, Directory.Build.props, src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/MetadataTests.cs, src/Basic.CompilerLog.UnitTests/PathNormalizationUtilTests.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/Basic.CompilerLog.Util.csproj, src/Basic.CompilerLog.Util/Basic.CompilerLog.Util.xml, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/Metadata.cs, src/Basic.CompilerLog.Util/PathNormalizationUtil.cs, src/Basic.CompilerLog.Util/Polyfill.cs, src/Scratch/Scratch.cs, src/Scratch/Scratch.csproj
When rehydrating on an OS with different paths from where the log was created the rehydration will normalize the paths for the current OS.
This is necessary for the compilation to function correctly. Items like parsing analyzer config options, classification, etc ... expect paths for the current OS and will fail otherwise.
=> Path normalization

src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/SolutionReaderTests.cs, src/Basic.CompilerLog.Util/Basic.CompilerLog.Util.xml, src/Basic.CompilerLog.Util/BasicAnalyzerHost.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostNone.cs, src/Basic.CompilerLog.Util/SolutionReader.cs
The `SolutionReader` was not promptly putting generated files into the `Project` when the none host was enabled. Looking into this made me realize the code wasn't treating none host strongly enough in a few places so fixed those as well.
=> Fix bug in none host

src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/RoslynUtilTests.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/Extensions.cs, src/Basic.CompilerLog.Util/Polyfill.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs
The `[ ... ]` in global editor configs have full paths written to them. That presents a problem when either: 
1. Opening a compiler log created on Windows in Linux (or vice versa)
2. Exporting a compiler log to disk
In both cases the paths of the files in the compilation will be different from the original values in the global config sections. Need to map them to keep it consistent. 
closes #110
=> Map global editor config sections

.vscode/settings.json, src/Basic.CompilerLog.UnitTests/BinaryLogUtilTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogBuilderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderExTests.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/BinaryLogUtil.cs, src/Basic.CompilerLog.Util/CompilerCall.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/CompilerLogUtil.cs, src/Basic.CompilerLog.Util/Serialize/MessagePackTypes.cs, src/Basic.CompilerLog/FilterOptionSet.cs, src/Basic.CompilerLog/Program.cs, src/Scratch/Scratch.cs
This stores the compiler used to build the binaries in the complog. 
`complog replay` will now warn when the compiler being used is older than the one the complog was built against
closes #83
=> Store compiler information

Directory.Packages.props, src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj, src/Basic.CompilerLog.UnitTests/BasicAnalyzerHostTests.cs, src/Basic.CompilerLog.UnitTests/BinaryLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerCallReaderUtilTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogUtilTests.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Basic.CompilerLog.Util/CompilerCallReaderUtil.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostNone.cs, src/Basic.CompilerLog.Util/RawCompilationData.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog.Util/Serialize/MessagePackTypes.cs, src/Basic.CompilerLog/Program.cs
Before this change using the None host with a binary log required round tripping to a compiler log first. Now it can just be done directly on a binary log.
=> Using the None host with binary logs

src/Basic.CompilerLog.UnitTests/BinaryLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CompilationDataTests.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/SolutionFixture.cs, src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog/Constants.cs, src/Basic.CompilerLog/Program.cs
Couple of changes
- Provide simple API for reading generated files from PDB (closes #125)
- New `generated` command that dumps generated files to disk
=> Support for manipulating generated files

Directory.Packages.props, src/Basic.CompilerLog.UnitTests/BasicAnalyzerHostTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/SolutionReaderTests.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Basic.CompilerLog.Util/CompilerCall.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostNone.cs, src/Basic.CompilerLog.Util/SolutionReader.cs, src/Scratch/CompilerBenchmarks.cs
1. The None host uses an in memory source generator
2. Fixed a few places paths were not normalized
closes #126
closes #127
=> Fixes a few issues

src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog.Util/Serialize/MessagePackTypes.cs, src/Basic.CompilerLog/Program.cs, src/Scratch/Scratch.cs
=> Include commit hash in compiler info

src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/TempDir.cs, src/Basic.CompilerLog/Program.cs
=> Generate response files inline

src/Basic.CompilerLog.UnitTests/BinaryLogUtilTests.cs, src/Basic.CompilerLog.Util/BinaryLogUtil.cs, src/Basic.CompilerLog/Properties/launchSettings.json, src/Scratch/Scratch.cs
Turns out the target framework can be included in `GlobalProperties` as well. Need to consult that when building up compilations.
=> Read TF out of GlobalProperties

src/Basic.CompilerLog.UnitTests/CompilationDataTests.cs, src/Basic.CompilerLog.Util/BinaryLogUtil.cs, src/Basic.CompilerLog.Util/CompilationData.cs
This fixes the following issue:
- #129 missed a case where `None` was special cased in `CompilationData`. That meant it double added `SyntaxTree` items. 
- Potential source of non-determinism as we're iterating a dictionary without sorting keys first.
closes #139
closes #140
=> Fix a couple of issues

src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Scratch/Scratch.cs
A scratch function I wrote to calculate the impact of assembly references in satellite compilations took nearly two minutes to execute. After profiling discovered it was due to repeated reads of the same files on disk. Added a simple cache to handle it.
=> Cache file reads in BinaryLogReader

src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/RawCompilationData.cs, src/Basic.CompilerLog.Util/ReferenceData.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog.Util/Serialize/MessagePackTypes.cs, src/Basic.CompilerLog/Program.cs
It would be useful to be able to quickly dump detailed information about analyzer versions from complogs, so we can immediately see, for example, what git commit of the razor compiler was used. This adds just that; we look for the assembly name and AssemblyInformationalVersionAttribute for each analyzer and record that information in the log for printing. We also do this for all references, since it goes through the same code path, but no display of that information is currently done.
=> Add analyzer assembly info printing

.gitignore, src/Basic.CompilerLog.UnitTests/RoslynUtilTests.cs, src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs
Simple change to only open a file once in a few cases instead of 2 or 3 times
=> Reduce IO a bit

.vscode/launch.json, .vscode/settings.json, src/Basic.CompilerLog.UnitTests/BasicAnalyzerHostTests.cs, src/Basic.CompilerLog.UnitTests/BinaryLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/BinaryLogUtilTests.cs, src/Basic.CompilerLog.UnitTests/CommonUtilTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogBuilderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderExTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/ExtensionsTests.cs, src/Basic.CompilerLog.UnitTests/FilterOptionSetTests.cs, src/Basic.CompilerLog.UnitTests/LogReaderState.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/StringStreamTests.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.Util/Basic.CompilerLog.Util.csproj, src/Basic.CompilerLog.Util/BasicAnalyzerHost.cs, src/Basic.CompilerLog.Util/CommonUtil.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogUtil.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostInMemory.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostOnDisk.cs, src/Basic.CompilerLog.Util/LogReaderState.cs, src/Basic.CompilerLog.Util/Polyfill.cs, src/Basic.CompilerLog.Util/StringStream.cs
Unix paths were accidentally being treated as options when exporting the RSP file. This lead to the RSP file being invalid as it had paths that weren't available the local machine (or even valid paths when crossing between operating systems).
The fix was fairly simple but testing it caused a decent amount of churn in the repository. Had to add APIs to make it possible to build up a compiler log in memory instead of off of disk.
=> Fix bug around unix paths

src/Basic.CompilerLog.UnitTests/BinaryLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerCallTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogBuilderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderExTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/Extensions.cs, src/Basic.CompilerLog.UnitTests/LibraryUtil.cs, src/Basic.CompilerLog.UnitTests/TempDir.cs, src/Basic.CompilerLog.Util/ExportUtil.cs
=> Fix link round tripping

src/Basic.CompilerLog.UnitTests/CompilerCallTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogBuilderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/Extensions.cs, src/Basic.CompilerLog.Util/BinaryLogUtil.cs, src/Basic.CompilerLog.Util/CompilerCall.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs
The `CompilerCall` API was hard to create in testing due to the order of arguments and how much it was geared towards efficient loading. This changes the constructor parameter order to be more natural and added an overload that much easier to use from testing.
=> Better API for CompilerCall

README.md, notes.txt, src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/FixtureBase.cs, src/Basic.CompilerLog.UnitTests/SolutionReaderTests.cs, src/Basic.CompilerLog.Util/CommonUtil.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/Metadata.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog.Util/Serialize/MessagePackTypes.cs, src/Basic.CompilerLog.Util/SolutionReader.cs, src/Directory.Build.props
This adds support for detecting project references when reading through the binlog. This is mostly based on matching a compiler call with its output binaries (by MVID) and then re-hydrating project references based off of that. 
closes #24
=> Support for project references

.github/workflows/dotnet.yml
Setup the CI so that it collects better logs when tests hang or timeout.
=> Test crash / timeout

src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj, src/Basic.CompilerLog/Basic.CompilerLog.csproj, src/Directory.Build.props, src/Directory.Packages.props, src/Scratch/Scratch.csproj
These CVE don't apply so using a suppression vs. changing build semantics
=> Use NuGetAuditSuppress

.vscode/launch.json, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Basic.CompilerLog/FilterOptionSet.cs, src/Scratch/Scratch.cs
The compilation name was being set to the full assembly name including the extension. That breaks IVT as compilation name is used for IVT checking and hence can't include the extension.
closes #187
=> Fix compilation name from binlog

src/Basic.CompilerLog.UnitTests/AppDomainUtils.cs, src/Basic.CompilerLog.UnitTests/AssertEx.cs, src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj, src/Basic.CompilerLog.UnitTests/BasicAnalyzerHostTests.cs, src/Basic.CompilerLog.UnitTests/BinaryLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CodeAnalysisExtensionTests.cs, src/Basic.CompilerLog.UnitTests/CompilationDataTests.cs, src/Basic.CompilerLog.UnitTests/CompilerCallReaderUtilTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogBuilderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderExTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogUtilTests.cs, src/Basic.CompilerLog.UnitTests/ConditionalFacts.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/Extensions.cs, src/Basic.CompilerLog.UnitTests/ExtensionsTests.cs, src/Basic.CompilerLog.UnitTests/FixtureBase.cs, src/Basic.CompilerLog.UnitTests/LogReaderStateTests.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/SolutionFixture.cs, src/Basic.CompilerLog.UnitTests/SolutionReaderTests.cs, src/Basic.CompilerLog.UnitTests/StringStreamTests.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Directory.Packages.props
Overall this was pretty straight forward after reading through the [migration guide](https://xunit.net/docs/getting-started/v3/migration). Biggest chunk of work was fixing up the xUnit1051 violations around `CancellationToken` but that was mostly mechanical. 
Did hit [one snag] in the .NET SDK when building. The fix turned out to be setting `<OutputType>Exe</OutputType>` explicitly in the xunit v3 project vs. depending on it to be set by the package.
=> Move to xUnit v3

src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/RoslynUtilTests.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Scratch/Scratch.cs
This uses `/` when writing paths to editor config section headers. Windows previously was using `\` and that gets treated as a literal escape, not a directory separator.
closes #197
=> Fix escaping of paths in editor config

.github/workflows/dotnet.yml, .github/workflows/test-report.yml, src/Basic.CompilerLog.UnitTests/AssertEx.cs, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/InMemoryLoaderTests.cs, src/Basic.CompilerLog.UnitTests/LogReaderStateTests.cs, src/Basic.CompilerLog.UnitTests/SolutionFixture.cs, src/Basic.CompilerLog.UnitTests/TestUtil.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/BasicAnalyzerHost.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostInMemory.cs, src/Basic.CompilerLog.Util/LogReaderState.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs
This change brings the in memory loader in line with how `AnalyzerFileReference` processes analyzers and generators. The code now uses `System.Reflection.Metadata` to scan for analyzer types in the assembly and then load only those into the process. This allows analyzer assemblies that have missing references that don't impact analyzers directly to still function. It also reduces the number of first chance exceptions generated in that scenario which significantly improves debugging.
=> Change in memory loading to better reflect how roslyn loads analyzers / generators

.vscode/launch.json, src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj, src/Basic.CompilerLog.UnitTests/BasicAnalyzerHostTests.cs, src/Basic.CompilerLog.UnitTests/InMemoryLoaderTests.cs, src/Basic.CompilerLog.UnitTests/LibraryUtil.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostInMemory.cs, src/Directory.Packages.props, src/Scratch/Scratch.cs, src/Scratch/Scratch.csproj
This makes the loader tolerant of analyzers / generators that have incorrect definitions. For example being attributed as an analyzer but not actually deriving from the correct type
closes #212
=> Fix handling analyzers with bad definitions

.github/workflows/dotnet.yml, src/Basic.CompilerLog.UnitTests/BinaryLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CompilationDataTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogBuilderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderExTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/ExportUtilTests.cs, src/Basic.CompilerLog.UnitTests/Extensions.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.UnitTests/TestUtil.cs, src/Basic.CompilerLog.Util/BinaryLogReader.cs, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/CompilerLogReader.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/Impl/BasicAdditionalTextFile.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostInMemory.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostNone.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostOnDisk.cs, src/Basic.CompilerLog.Util/RawCompilationData.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog.Util/SdkUtil.cs, src/Basic.CompilerLog.Util/Serialize/MessagePackTypes.cs
This changes compiler logs to be more tolerant of missing disk artifacts. The old strategy was to simply error and bail out when artifacts were missing on disk. This was designed primarily to make sure customers weren't creating and submitting _stale_ binary logs.
Diagnostics around potentially _stale_ logs are valuable but it was too agressive. It meant that the tooling couldn't represent `Compilations` with those types of errors. For example: instead of creating a `Compilation` where emit fails because of a missing key file the tooling just could not create a `Compilation` at all.
This change is pushing the tooling to be tolerant of the missing artifacts while preserving the _stale_ diagnostics in `complog create`.
closes #217
=> Tolerance for missing files

src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/UsingAllCompilerLogTests.cs, src/Basic.CompilerLog.Util/CodeAnalysisExtensions.cs, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog/Program.cs, src/Scratch/Scratch.cs
When building with embedded PDBs the `Emit*` methods were incorrectly passing a `Stream` for the PDB. That is not needed as the PDB is written into the PE file directly
=> Embedded PDB do not need streams

src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/MiscDirectory.cs, src/Scratch/Scratch.cs
The source root during export needs to consider editorconfig files that may exist _above_ the project file.
=> Fix exporting complex paths

src/Basic.CompilerLog.UnitTests/LibraryUtil.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/RoslynUtilTests.cs, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Basic.CompilerLog.Util/Extensions.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostInMemory.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog/Program.cs
Adds the option to include analyzer / generator type names in the `complog analyzers` output.
=> Option to include analyzer / generator type names 

.devcontainer/Dockerfile, .github/workflows/dotnet.yml, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.UnitTests/TestUtil.cs, src/Basic.CompilerLog.UnitTests/xunit.runner.json, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog.Util/CompilerLogBuilder.cs, src/Basic.CompilerLog.Util/Extensions.cs, src/Basic.CompilerLog/Program.cs, src/Scratch/Scratch.cs
This adds a command to print compilation ids: both the raw content id and the checksum version, for each compilation. These IDs represent the compilation in text form. Two equal compilations will have the same ID.
=> Ability to capture compilation ids

.devcontainer/devcontainer.json, .github/workflows/dotnet.yml, src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj, src/Basic.CompilerLog.UnitTests/BinaryLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogFixture.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/SolutionFixture.cs, src/Basic.CompilerLog.UnitTests/TempDir.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.UnitTests/TestUtil.cs, src/Basic.CompilerLog.UnitTests/UnitTestsTests.cs
Log more content hash files so that we can diff locally to tests to see what the differences are.
=> Log more content hash files

src/Basic.CompilerLog.UnitTests/BasicAnalyzerHostTests.cs, src/Basic.CompilerLog.UnitTests/CompilationDataTests.cs, src/Basic.CompilerLog.UnitTests/CompilerLogReaderTests.cs, src/Basic.CompilerLog.UnitTests/Extensions.cs, src/Basic.CompilerLog.UnitTests/InMemoryLoaderTests.cs, src/Basic.CompilerLog.UnitTests/LibraryUtil.cs, src/Basic.CompilerLog.UnitTests/LogReaderStateTests.cs, src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog.UnitTests/RoslynUtilTests.cs, src/Basic.CompilerLog.UnitTests/SolutionReaderTests.cs, src/Basic.CompilerLog.UnitTests/TestBase.cs, src/Basic.CompilerLog.UnitTests/TestUtil.cs, src/Basic.CompilerLog.Util/BannedSymbols.txt, src/Basic.CompilerLog.Util/Basic.CompilerLog.Util.csproj, src/Basic.CompilerLog.Util/BasicAnalyzerHost.cs, src/Basic.CompilerLog.Util/CommonUtil.cs, src/Basic.CompilerLog.Util/CompilationData.cs, src/Basic.CompilerLog.Util/Data.cs, src/Basic.CompilerLog.Util/Extensions.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostInMemory.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostNone.cs, src/Basic.CompilerLog.Util/Impl/BasicAnalyzerHostOnDisk.cs, src/Basic.CompilerLog.Util/LogReaderState.cs, src/Basic.CompilerLog.Util/RoslynUtil.cs, src/Basic.CompilerLog/Program.cs, src/Directory.Packages.props, src/Scratch/Scratch.cs
When analyzers / generators produce diagnostics put it in the hash content so that it's visible in the diff
=> Remove silent failure of hash

src/Basic.CompilerLog.UnitTests/ProgramTests.cs, src/Basic.CompilerLog/Program.cs
By defaut shift to printing short name for readability and added an explicit `--path` option to see the full paths.
=> Print short name in analyzers

.github/workflows/publish.yml
Try running `complog help` with the latest package version. You will get
```
complog [command] [args]
version: 42.42.42.42
```
whereas after this PR is merged and released you should get
```
complog [command] [args]
version: 0.9.14.0
```
=> Fix version not being included in the package

src/Directory.Packages.props
The warning is pretty annoying:
=> Suppress warning about missing package sources

src/Basic.CompilerLog.Util/Basic.CompilerLog.Util.csproj, src/Basic.CompilerLog.Util/ExportUtil.cs, src/Directory.Packages.props
Without this, complog selects 9.0 sdk over 10.0. That's also impacting my ability to run ExportUtil tests locally because they use 10 sdk for building but then run against 9 sdk, failing with "lang version 14 is not valid".
=> Use natural sort to select the best SDK

src/Basic.CompilerLog.Util/ExportUtil.cs
`/sourcelink` is handled in the code path which copies source files and rewrites the paths, but it wasn't skipped here, leading to the exported rsp containing both the original `/sourcelink` (with absolute path to the machine where the complog was collected) and the rewritten `/sourcelink` (the correct one, no changes to that one in this PR).
=> Avoid exporting `/sourcelink` absolute path
